#!/bin/bash
# Remote Server Setup and Execution Commands
# Server: jiuzhou@er074.utah.cloudlab.us

echo "=========================================="
echo "Step 1: Upload Data Files"
echo "=========================================="
echo ""
echo "从本地Windows执行以下命令（在PowerShell中）："
echo ""
echo "cd \"D:\\My notes\\UW\\HPDIC Lab\\MPAD\\PCA vs DW_PMAD\\PCA vs DW_PMAD\""
echo ""
echo "# 上传完整的训练数据（1% Fasttext，应该有约8000个样本）"
echo "scp training_vectors_01pct_Fasttext.npy jiuzhou@er074.utah.cloudlab.us:~/Approximate/"
echo ""
echo "# 上传优化的MPAD脚本"
echo "scp Approximate/mpad_optimized.py jiuzhou@er074.utah.cloudlab.us:~/Approximate/"
echo "scp Approximate/test_optimized_mpad.py jiuzhou@er074.utah.cloudlab.us:~/Approximate/"
echo "scp Approximate/main_program.py jiuzhou@er074.utah.cloudlab.us:~/Approximate/"
echo ""
echo "# 或者使用pscp（如果安装了PuTTY）"
echo "pscp training_vectors_01pct_Fasttext.npy jiuzhou@er074.utah.cloudlab.us:~/Approximate/"
echo ""
echo "=========================================="
echo "Step 2: Verify Data on Remote Server"
echo "=========================================="
echo ""
echo "# SSH到远程服务器"
echo "ssh jiuzhou@er074.utah.cloudlab.us"
echo ""
echo "# 检查文件大小和内容"
echo "cd ~/Approximate"
echo "ls -lh training_vectors_01pct_Fasttext.npy"
echo "python3 -c \"import numpy as np; x = np.load('training_vectors_01pct_Fasttext.npy'); print(f'Shape: {x.shape}')\""
echo ""
echo "# 应该显示类似："
echo "# Shape: (7999, 300) 或者接近这个数字"
echo ""
echo "=========================================="
echo "Step 3: Install Dependencies"
echo "=========================================="
echo ""
echo "# 安装Numba（如果还没安装）"
echo "pip install --user numba"
echo ""
echo "# 验证安装"
echo "python3 -c \"import numba; print(f'Numba version: {numba.__version__}')\""
echo ""
echo "=========================================="
echo "Step 4: Set Environment Variables"
echo "=========================================="
echo ""
echo "export OMP_NUM_THREADS=1"
echo "export MKL_NUM_THREADS=1"
echo "export OPENBLAS_NUM_THREADS=1"
echo "export NUMEXPR_NUM_THREADS=1"
echo "export NUMBA_THREADING_LAYER=omp"
echo "export OMP_PROC_BIND=close"
echo "export OMP_PLACES=cores"
echo ""
echo "=========================================="
echo "Step 5: Run Test"
echo "=========================================="
echo ""
echo "cd ~/Approximate"
echo "python3 test_optimized_mpad.py"
echo ""
echo "=========================================="
echo "Step 6: Download Results (from local)"
echo "=========================================="
echo ""
echo "# 如果生成了结果文件，从本地下载："
echo "scp jiuzhou@er074.utah.cloudlab.us:~/Approximate/*.csv ."
echo ""

